### ISSUE TITLE
Build Server Protocol maybe?

### ISSUE THREAD

**Issue by 616b2f** [Zeioth/compiler.nvim#17]
Hi,

recently I read the article at Reddit:

https://www.reddit.com/r/neovim/comments/17hi6s6/build_server_protocol_lsp_like_protocol_for/

Which talks about the Build Server Protocol (BSP):

https://build-server-protocol.github.io/

This could be a neat addition to this plugin IF it get's more attraction, currently there are not many BSP servers available.

It's fine if it's out of scope, I just wanted to bring this to your attention. What do you think?

**Comment by Zeioth** [comment]
Thank you for pointing me to that protocol @616b2f !

Initially build automation utilities support was out of scope for us because strictly speaking is not really the responsibility of a compiler, but out of practicality for the final user I've decided to add it.

There are many tools and it's gonna take a while to add them. But after that I can look into build servers.

It would really help if I can find any other neovim plugin that already implement the protocol.

**Comment by 616b2f** [comment]
Thank you for the response. Currently I am not aware of any neovim plugin that implements it and your plugin comes closest to the user experience they try to provide, that's why I decided to open the issue here. I also didn't saw any lua bindings for it unfortunately. I could open an issue on they repo, maybe if there are enough interest they could create lua bindings.

**Comment by Zeioth** [comment]
Moving this from issues to discussions https://github.com/Zeioth/compiler.nvim/discussions/18
