### ISSUE TITLE
Windows support requires WLS at the moment (Windows Linux Subsystem)

### ISSUE THREAD

**Issue by TimeCubed** [Zeioth/compiler.nvim#2]
Although the title might look like a joke, it's really not doing anything.
I tried to run `:CompilerOpen` on a hello world app in C++ but it just wouldn't compile anything. Here's an 
[image](https://github.com/Zeioth/compiler.nvim/assets/48620951/ed70798a-eaf6-4caa-a4a4-b6bfd6499324) that shows this.
I waited for a while and nothing ended up happening. There's also a couple issues with your README.MD file. The plugin requires telescope.nvim as well as plenary.nvim installed and loaded, both of which you failed to mention. Other than that, this is the one issue I'm having a ton of problems with, and I have no idea what to do about it. Please help me.

**Comment by SummerNugget** [comment]
Just for clarification: the directory in the image is correct. I was editing my neovim layout. It's also important to mention that I'm using Windows 11 64 bit.

**Comment by Zeioth** [comment]
For what I can see in your image, the error  seems to be that to properly support Windows, we need to take care of using \ instead of / on Windows.

I will fix it with a library to use \ or / depending of the operative system. Thank you for reporting @SummerNugget, I will look into it. 

In the mean time, if you are in a hurry, try to launch neovim using the Windows Linux Subsystem and it should work fine.
