### ISSUE TITLE
New Language Request: SystemVerilog

### ISSUE THREAD

**Issue by Myron2812** [Zeioth/compiler.nvim#25]
Hello There!

I would to ask if you could possibly add support for SystemVerilog? I'm pretty new to this so I'm not really sure if it will work but I've attached a link to a suitable compiler:
https://verilator.org/guide/latest/index.html

Do let me know if it's possible or if I can be of any help. Thanks in advance!

**Comment by Zeioth** [comment]
Currently it is low prio because I want to add buid automation utilities such as maven first, but if you wanna send a PR ask me anything. You can learn how to add support for a new language or build automation system in the [FAQ](https://github.com/Zeioth/compiler.nvim#faq).

You have a example of adding support for a new language in [this PR](https://github.com/Zeioth/compiler.nvim/pull/23/commits/03ece431f42e0e25382bd3eeaca9aa18909874f9)

**Comment by Myron2812** [comment]
Thanks for pointing me to the right resources! I will try working on this.

**Comment by Zeioth** [comment]
Closing for now. Feel free to re-open in the future.
