### ISSUE TITLE
Meson integration

### ISSUE THREAD

**Issue by speediegq** [Zeioth/compiler.nvim#29]
Would be really cool if this plugin could find `meson.build` and use it.

**Comment by Zeioth** [comment]
@speediegq Added to the roadmap, thank you for reporting.

In case you are in a hurry and want to send a PR yourself, you only need to touch the files:

* `lua/compiler/utils-bau.lua` → Implement a parser function that parse the options defined in your meson file. Then call it at the end of the function `M.get_bau_opts()`.
* `lua/compiler/bau/meson.lua` → Here you implement what happens when a user select one of the options defined in your meson file. You can take `./cmake.lua` as reference.

Otherwise expect it at some point during this month probably. This week I'm working on the new plugin [distroupdate.nvim](https://github.com/Zeioth/distroupdate.nvim).

**Comment by Zeioth** [comment]
Added in https://github.com/Zeioth/compiler.nvim/commit/b34e79d4afb371b718a5c2b8dcbc638aa75411c1
