### ISSUE TITLE
Use vim.ui.select intead of telescope

### ISSUE THREAD

**Issue by xyven1** [Zeioth/compiler.nvim#44]
I do not use telescope, and honestly `vim.ui.select` is should be used whenever picking from a list is required. This makes it easy for to set the UI to whatever I want (such as `fzf-lua`), [including telescope](https://github.com/nvim-telescope/telescope-ui-select.nvim)! It also means that it would work with the default neovim picker.

While this would make the plugin much more flexible, I understand if it would decrease the functionality too much to be worth it. If that is the case I would appreciate if `fzf-lua` support was added, as I that plugin also has lots of use.

If this is not amenable to the project, then at the very least add telescope as a dependency in the README, and mention it somewhere other than in the source code itself.

**Comment by Zeioth** [comment]
The issue is, we are passing data to telescope on a format it can understand, so changing to a different selector wouldn't probably translate well. But I've written the project in a way if you fork the project, it is feasible to use a different frontend, because I've considered we might have to change it in the future. 

About the dependency you are absolutely right, adding it to the readme.
